"use client";

import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Loader2, Wand2, RefreshCw } from "lucide-react";
import { toast } from "sonner";

interface RegenerateDayDialogProps {
  dayId?: string;
  dayNumber: number;
  destination: string;
  currentTheme?: string;
  isOpen: boolean;
  onClose: () => void;
  onRegenerated: (updatedDay: any) => void;
}

const PRESET_CHIPS = [
  { label: "🌧️ Rainy-day friendly", prompt: "Rainy-day friendly: prioritize covered museums, galleries, and cozy historic cafes." },
  { label: "🍽️ Culinary highlights", prompt: "Foodie adventure: focus on acclaimed local eateries, street food, and authentic food markets." },
  { label: "🌿 Scenic & outdoors", prompt: "Scenic & relaxing: prioritize parks, waterfronts, viewpoint gardens, and strolls." },
  { label: "⚡ High-energy pace", prompt: "Action-packed: hit iconic must-see monuments efficiently with minimal downtime." },
  { label: "🍸 Nightlife & vibe", prompt: "Evening excitement: focus on sunset viewpoints, rooftop lounges, and vibrant nightlife." },
  { label: "🎨 Cultural & hidden gems", prompt: "Off-the-beaten-path: explore artisan workshops, local indie boutiques, and hidden historic alleys." },
];

export function RegenerateDayDialog({
  dayId,
  dayNumber,
  destination,
  currentTheme,
  isOpen,
  onClose,
  onRegenerated,
}: RegenerateDayDialogProps) {
  const [customPrompt, setCustomPrompt] = useState("");
  const [selectedChip, setSelectedChip] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleChipClick = (chip: typeof PRESET_CHIPS[0]) => {
    if (selectedChip === chip.label) {
      setSelectedChip(null);
      setCustomPrompt("");
    } else {
      setSelectedChip(chip.label);
      setCustomPrompt(chip.prompt);
    }
  };

  const handleRegenerate = async () => {
    if (!dayId) {
      toast.error("Cannot regenerate this day: missing day identifier");
      return;
    }

    setIsLoading(true);
    try {
      const promptToSend = customPrompt.trim();
      const res = await fetch(`/api/days/${dayId}/regenerate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          preferences: promptToSend || undefined,
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || "Failed to regenerate day");
      }

      onRegenerated(data.data);
      toast.success(`Day ${dayNumber} successfully regenerated by AI!`);
      onClose();
    } catch (err: any) {
      console.error("Day regeneration error:", err);
      toast.error(err?.message || "Failed to regenerate day");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && !isLoading && onClose()}>
      <DialogContent className="max-w-md border-border/80 bg-background/95 backdrop-blur-xl shadow-2xl rounded-2xl">
        <DialogHeader className="space-y-1">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
              <Sparkles className="w-4 h-4" />
            </div>
            <DialogTitle className="text-xl font-bold tracking-tight">
              Regenerate Day {dayNumber}
            </DialogTitle>
          </div>
          <DialogDescription className="text-sm text-muted-foreground">
            Rebuild stops for Day {dayNumber} in {destination}. Choose a theme or provide custom instructions.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {currentTheme && (
            <div className="text-xs text-muted-foreground flex items-center gap-1.5">
              <span>Current Theme:</span>
              <span className="font-semibold text-foreground bg-muted/60 px-2 py-0.5 rounded-md border border-border/40">
                {currentTheme}
              </span>
            </div>
          )}

          {/* Preset Chips */}
          <div className="space-y-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">
              Quick Suggestions
            </label>
            <div className="flex flex-wrap gap-1.5">
              {PRESET_CHIPS.map((chip) => {
                const isSelected = selectedChip === chip.label;
                return (
                  <button
                    key={chip.label}
                    type="button"
                    onClick={() => handleChipClick(chip)}
                    className={`text-xs px-2.5 py-1.5 rounded-xl border transition-all ${
                      isSelected
                        ? "bg-primary text-primary-foreground border-primary font-medium shadow-sm"
                        : "bg-muted/40 hover:bg-muted text-foreground border-border/60"
                    }`}
                  >
                    {chip.label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Custom Prompt Textarea */}
          <div className="space-y-1.5">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">
              Custom AI Guidance (Optional)
            </label>
            <Textarea
              rows={3}
              value={customPrompt}
              onChange={(e) => {
                setCustomPrompt(e.target.value);
                setSelectedChip(null);
              }}
              placeholder="e.g. Include a relaxed canal boat tour and vegetarian lunch near the museum..."
              className="rounded-xl resize-none text-sm"
              disabled={isLoading}
            />
          </div>
        </div>

        <DialogFooter className="pt-2 gap-2 sm:gap-0">
          <Button
            type="button"
            variant="outline"
            onClick={onClose}
            className="rounded-xl"
            disabled={isLoading}
          >
            Cancel
          </Button>
          <Button
            type="button"
            onClick={handleRegenerate}
            disabled={isLoading}
            className="rounded-xl bg-primary text-primary-foreground font-semibold shadow-md shadow-primary/20"
          >
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Crafting Day {dayNumber}...
              </>
            ) : (
              <>
                <Wand2 className="w-4 h-4 mr-1.5" />
                Regenerate Day
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
